name: Deploy to Github Pages

inputs:
  publish_dir:
    description: A source directory to deploy to GitHub Pages.
    required: false
  destination_dir:
    description: A destination subdirectory on a publishing branch.
    required: false

runs:
  using: composite    
  steps:
    uses: actions/checkout@v4
    uses: peaceiris/actions-gh-pages@v4
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ${{ inputs.publish_dir }}
      destination_dir: ${{ inputs.destination_dir }}
      full_commit_message: "Build for ${{ github.sha }} ${{ github.event.head_commit.message }}"